### PR TITLE
Update organizing.md

### PR DESCRIPTION
**Pull request by friedger**
Add a section about sponsorship and legal entities.

### CODE REVIEW

**Comment by stefanhoth** [comment]
:+1:

**Comment by erickmendonca** [comment]
:+1: 
I think that ask for things or services instead of money is a good idea everywhere. Saves a lot of time and hassle.

**Comment by knyaoga** [comment]
:+1: 
It is always easy to have a request on facilitation approved as opposed to money. So we need to major on services as Erick has put it.

**Comment by kenju254** [comment]
@friedger Looks fine. Will be merging this.

**Pull request merged**
