### PR TITLE
Update mentors.md

### PR DESCRIPTION
**Pull request by kenju254**
Answered Questions regarding GDG Mentors.

### CODE REVIEW

**Comment by kenju254** [comment]
@nitya  and @friedger  kindly have a look at the Mentors page that has been updated.

**Comment by friedger** [comment]
Could you be more specific about how to become a mentor? Is there a process coordinated by Google? Is this a Google initiative? 

In German speaking region, we have chapter buddies for incubating chapters. A buddy is very informal and based on volunteering.

**Comment by kenju254** [comment]
@friedger Cool. Let me be more clear in how to become a GDG Mentor.. But yes there is a Google Process in the regions available.. GDG Organizers in a certain region nominate a GDG Organizer who they think is fit to join the program and then there is a vote. The winning GDG becomes a Mentor. All this is facilitated by Google.

**Comment by friedger** [comment]
Do you know which regions?
Am 12.07.2015 10:27 schrieb "Kenneth Kinyanjui" notifications@github.com:

**Comment by kenju254** [comment]
@friedger yes I do know a couple of regions where it working .. But i will need to confirm.  I am sure of SSA since I am a GDG Country Mentor for Kenya

**Pull request merged**
